### ISSUE TITLE
Issue interacting with access points

### ISSUE THREAD

**Issue by not-senate** [cardinal-dev/Cardinal#182]
I was able to get the docker version running and it allowed me to add a 1142N access point but when trying to do anything with the AP ie fetch information I got the below error which seems similar to Issue: cardinal-dev/cardinal-docker#2 , Thanks in advance!

cardinal_1  | [2022-04-16 02:33:54,314] ERROR in app: Exception on /get-ap-info [POST]
cardinal_1  | Traceback (most recent call last):
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
cardinal_1  |     response = self.full_dispatch_request()
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
cardinal_1  |     rv = self.handle_user_exception(e)
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
cardinal_1  |     rv = self.dispatch_request()
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
cardinal_1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
cardinal_1  |   File "/opt/Cardinal/webapp/./cardinal/views/cardinal_ap_ops.py", line 150, in fetchApInfo
cardinal_1  |     status = gatherApInfo(apId)
cardinal_1  |   File "/opt/Cardinal/webapp/./cardinal/system/cardinal_fetch.py", line 57, in gatherApInfo
cardinal_1  |     apInfo = info.fetcher(ip=apIp, username=apSshUsername, password=apSshPassword)
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/scout/info.py", line 197, in fetcher
cardinal_1  |     jinjaEnv = scout.env.scoutJinjaEnv()
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/scout/env.py", line 41, in scoutJinjaEnv
cardinal_1  |     scoutConfigFile = os.environ['SCOUTCONFIG']
cardinal_1  |   File "/usr/lib/python3.8/os.py", line 675, in __getitem__
cardinal_1  |     raise KeyError(key) from None
cardinal_1  | KeyError: 'SCOUTCONFIG'
cardinal_1  | [pid: 25|app: 0|req: 11/42] 10.0.0.10 () {50 vars in 1051 bytes} [Sat Apr 16 02:33:53 2022] POST /get-ap-info => generated 290 bytes in 685 msecs (HTTP/1.1 500) 3 headers in 113 bytes (1 switches on core 0)

**Comment by falcon78921** [comment]
Hey @not-senate :wave:

Sorry for the delay. I just merged the following PR to the Cardinal codebase: https://github.com/cardinal-dev/Cardinal/pull/166

In order to get Cardinal positioned for a CI/CD workflow, I created a docker-compose deployment inside cardinal-dev/Cardinal. The docker-compose deployment is specifically for CI/CD testing, however, you could use it to test Cardinal with the latest source. Right now, I'm putting the brakes on `cardinal-docker` temporarily. I will return to this once a roadmap is more defined. 

If you want to test Cardinal using the docker-compose deployment for CI/CD, you can clone https://github.com/cardinal-dev/Cardinal.git and then execute the following inside:

```
docker-compose build
docker-compose up
```

**Comment by falcon78921** [comment]
I'm going to close this issue out for now. If you still have any questions/issues, please feel free to follow-up here and we can always re-open. Thanks! :)
